# Fly.io configuration for voice server
app = "ikigai-voice-server"
primary_region = "iad"  # Virginia - good for US mobile users

[build]

[env]
  NODE_ENV = "production"
  PORT = "3001"

[[services]]
  protocol = "tcp"
  internal_port = 3001
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [services.concurrency]
    type = "connections"
    hard_limit = 1000
    soft_limit = 1000

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "1s"

  [services.http_checks]
    interval = "10s"
    timeout = "2s"
    grace_period = "1s"
    method = "get"
    path = "/health"
    protocol = "http"
    tls_skip_verify = false

# Mobile-optimized settings
[experimental]
  auto_rollback = true

[deploy]
  release_command = "echo 'Voice server starting...'"
  strategy = "rolling"
